### ISSUE TITLE
OSError: [Errno 45] Operation not supported: '/home/bach'

### ISSUE THREAD

**Issue by Danissss** [aalto-ics-kepaco/retention_order_prediction#1]
Hi, 

I encountered following error while executing 
`python src/evaluation_scenarios_main.py ranksvm baseline_single 10 -1 results/raw/PredRet/v2/config.json 2 False`

```
/Users/xuan/miniconda3/envs/retentionCal/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)
Traceback (most recent call last):
  File "src/evaluation_scenarios_main.py", line 502, in <module>
    os.makedirs (output_dir)
  File "/Users/xuan/miniconda3/envs/retentionCal/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/Users/xuan/miniconda3/envs/retentionCal/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/Users/xuan/miniconda3/envs/retentionCal/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 14 more times]
  File "/Users/xuan/miniconda3/envs/retentionCal/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
OSError: [Errno 45] Operation not supported: '/home/bach'
```

**Comment by bachi55** [comment]
Hi Danissss,

you need to change the `config.json`: The "base_dir" needs to be changed to a file-path you have read / write access to. Hard coding it in that example was probably not the best idea. 

Best regards,
Eric

**Comment by Danissss** [comment]
Thank you!
